services:
  - type: redis
    name: votefusion-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
    region: frankfurt

  - type: web
    name: votefusion-api
    env: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: >
      npm install && cd shared && npm install && npm run build && cd ../server && 
      npm install -g @nestjs/cli && npm install && 
      npm run build -- --path tsconfig.build.json
    startCommand: cd server && NODE_PATH=../shared/dist node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CLIENT_PORT
        value: 10000
      - key: REDIS_HOST
        fromService:
          type: redis
          name: votefusion-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: votefusion-redis
          property: port
      - key: TS_NODE_BASEURL
        value: ./dist

  - type: web
    name: votefusion-client
    env: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: >
      npm install && cd shared && npm install && npm run build && cd ../client && 
      npm install && 
      npm install --save-dev @types/react-transition-group @types/react @types/react-dom @types/storybook__react @types/jest && 
      rm -rf src/stories && 
      SKIP_PREFLIGHT_CHECK=true NODE_ENV=production npm run build
    startCommand: cd client && npm run serve
    envVars:
      - key: VITE_API_URL
        value: https://votefusion-api.onrender.com
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: SKIP_PREFLIGHT_CHECK
        value: "true"
